// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Appets.DataAccess.Entities
{
    public partial class tbAlbergue
    {
        public int alberg_Id { get; set; }
        public string alberg_RTN { get; set; }
        public string alberg_Nombre { get; set; }
        public string alberg_Ubicacion { get; set; }
        public string alberg_Telefono { get; set; }
        public string alberg_Correo { get; set; }
        public string alberg_Mision { get; set; }
        public string alberg_InformacionAdicion { get; set; }
    }
}