// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Appets.DataAccess.Entities
{
    public partial class tbDonantes
    {
        public int don_Id { get; set; }
        public int per_Id { get; set; }
        public DateTime don_Fecha { get; set; }
        public string don_Descripcion { get; set; }

        public virtual tbPersonas per { get; set; }
    }
}