// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Appets.DataAccess.Entities
{
    public partial class tbEmpleados
    {
        public tbEmpleados()
        {
            tbMascotas = new HashSet<tbMascotas>();
        }

        public int emp_Id { get; set; }
        public int per_Id { get; set; }
        public int ocup_Id { get; set; }
        public bool? EsEliminado { get; set; }

        public virtual ICollection<tbMascotas> tbMascotas { get; set; }
    }
}