// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Appets.DataAccess.Entities
{
    public partial class tbEspecies
    {
        public tbEspecies()
        {
            tbMascotas = new HashSet<tbMascotas>();
            tbRazas = new HashSet<tbRazas>();
        }

        public int espc_Id { get; set; }
        public string espc_Descripcion { get; set; }

        public virtual ICollection<tbMascotas> tbMascotas { get; set; }
        public virtual ICollection<tbRazas> tbRazas { get; set; }
    }
}