// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Appets.DataAccess.Entities
{
    public partial class tbFichaMedica
    {
        public int medic_Id { get; set; }
        public int masc_Id { get; set; }
        public bool medic_Esterilizacion { get; set; }
        public string medic_Personalidad { get; set; }
        public string medic_SaludCuidado { get; set; }
        public string medic_InformacionAdicional { get; set; }
        public bool? EsEliminado { get; set; }

        public virtual tbMascotas masc { get; set; }
    }
}