// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Appets.DataAccess.Entities
{
    public partial class tbFichaAdopcion
    {
        public int ficha_Id { get; set; }
        public int masc_Id { get; set; }
        public int per_Id { get; set; }
        public DateTime ficha_FechaRegistro { get; set; }
        public int? EsEliminado { get; set; }

        public virtual tbMascotas masc { get; set; }
        public virtual tbPersonas per { get; set; }
    }
}