// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Appets.DataAccess.Entities
{
    public partial class tbMascotas
    {
        public tbMascotas()
        {
            tbFichaAdopcion = new HashSet<tbFichaAdopcion>();
            tbFichaMedica = new HashSet<tbFichaMedica>();
            tbSolicitud = new HashSet<tbSolicitud>();
        }

        public int masc_Id { get; set; }
        public string masc_Imagen { get; set; }
        public string masc_Nombre { get; set; }
        public int espc_Id { get; set; }
        public int raza_Id { get; set; }
        public int masc_Edad { get; set; }
        public string masc_Sexo { get; set; }
        public string masc_Peso { get; set; }
        public string masc_Talla { get; set; }
        public string masc_Color { get; set; }
        public int emp_Id { get; set; }
        public bool? masc_EsAdoptado { get; set; }
        public bool? masc_EsReservado { get; set; }
        public string masc_HistorialDescripcion { get; set; }
        public int proc_Id { get; set; }
        public bool? EsEliminado { get; set; }

        public virtual tbEmpleados emp { get; set; }
        public virtual tbEspecies espc { get; set; }
        public virtual tbProcedencia proc { get; set; }
        public virtual tbRazas raza { get; set; }
        public virtual ICollection<tbFichaAdopcion> tbFichaAdopcion { get; set; }
        public virtual ICollection<tbFichaMedica> tbFichaMedica { get; set; }
        public virtual ICollection<tbSolicitud> tbSolicitud { get; set; }
    }
}