// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Appets.DataAccess.Entities
{
    public partial class tbModuloPantallas
    {
        public tbModuloPantallas()
        {
            tbRolModuloPantallas = new HashSet<tbRolModuloPantallas>();
        }

        public int modpan_Id { get; set; }
        public int? mod_Id { get; set; }
        public string modpan_Nombre { get; set; }

        public virtual tbModulos mod { get; set; }
        public virtual ICollection<tbRolModuloPantallas> tbRolModuloPantallas { get; set; }
    }
}