// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Appets.DataAccess.Entities
{
    public partial class tbOcupaciones
    {
        public int ocup_Id { get; set; }
        public string ocup_Descripcion { get; set; }
    }
}