// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Appets.DataAccess.Entities
{
    public partial class tbProcedencia
    {
        public tbProcedencia()
        {
            tbMascotas = new HashSet<tbMascotas>();
        }

        public int proc_Id { get; set; }
        public string proc_Descripcion { get; set; }

        public virtual ICollection<tbMascotas> tbMascotas { get; set; }
    }
}