// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Appets.DataAccess.Entities
{
    public partial class tbRazas
    {
        public tbRazas()
        {
            tbMascotas = new HashSet<tbMascotas>();
        }

        public int raza_Id { get; set; }
        public string raza_Descripcion { get; set; }
        public int? espc_Id { get; set; }

        public virtual tbEspecies espc { get; set; }
        public virtual ICollection<tbMascotas> tbMascotas { get; set; }
    }
}