// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Appets.DataAccess.Entities
{
    public partial class tbRoles
    {
        public tbRoles()
        {
            tbRolModuloPantallas = new HashSet<tbRolModuloPantallas>();
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int rol_Id { get; set; }
        public string rol_Nombre { get; set; }
        public bool rol_EsActivo { get; set; }

        public virtual ICollection<tbRolModuloPantallas> tbRolModuloPantallas { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}