// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Appets.DataAccess.Entities
{
    public partial class tbRolModuloPantallas
    {
        public int modpan_Id { get; set; }
        public int rol_Id { get; set; }

        public virtual tbModuloPantallas modpan { get; set; }
        public virtual tbRoles rol { get; set; }
    }
}