// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Appets.DataAccess.Entities
{
    public partial class tbVoluntarios
    {
        public int volun_Id { get; set; }
        public int per_Id { get; set; }
        public DateTime volun_FechaIngreso { get; set; }
        public bool? EsEliminado { get; set; }

        public virtual tbPersonas per { get; set; }
    }
}