// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Appets.DataAccess.Entities
{
    public partial class UDP_tbFichaAdopcion_SelectResult
    {
        public int ficha_Id { get; set; }
        public int masc_Id { get; set; }
        public string masc_Nombre { get; set; }
        public int per_Id { get; set; }
        public string per_Nombres { get; set; }
        public string per_Apellidos { get; set; }
        public DateTime ficha_FechaRegistro { get; set; }
    }
}
