// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Appets.DataAccess.Entities
{
    public partial class UDP_tbUsuarios_SelectResult
    {
        public int usu_Id { get; set; }
        public string usu_Identidad { get; set; }
        public string usu_PrimerNombre { get; set; }
        public string usu_PrimerApellido { get; set; }
        public string usu_SegundoNombre { get; set; }
        public string usu_SegundoApellido { get; set; }
        public string usu_Telefono { get; set; }
        public byte[] usu_Contraseña { get; set; }
        public int rol_Id { get; set; }
        public string rol_Nombre { get; set; }
        public bool usu_EsActivo { get; set; }
    }
}
