// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Appets.DataAccess.Entities
{
    public partial class UDP_tbVoluntarios_SelectResult
    {
        public int volun_Id { get; set; }
        public int per_Id { get; set; }
        public string per_Nombres { get; set; }
        public string per_Apellidos { get; set; }
        public DateTime volun_FechaIngreso { get; set; }
    }
}
