// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Appets.DataAccess.Entities
{
    public partial class UDP_tbMascotas_SelectResult
    {
        public int masc_Id { get; set; }
        public string masc_Nombre { get; set; }
        public int espc_Id { get; set; }
        public string espc_Descripcion { get; set; }
        public int raza_Id { get; set; }
        public string raza_Descripcion { get; set; }
        public int masc_Edad { get; set; }
        public string masc_Sexo { get; set; }
        public string masc_Peso { get; set; }
        public string masc_Talla { get; set; }
        public string masc_Color { get; set; }
        public int emp_Id { get; set; }
        public string per_Nombres { get; set; }
        public string per_Apellidos { get; set; }
        public bool? masc_EsAdoptado { get; set; }
        public bool? masc_EsReservado { get; set; }
        public string masc_HistorialDescripcion { get; set; }
        public int proc_Id { get; set; }
        public string proc_Descripcion { get; set; }
    }
}
