// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Appets.DataAccess.Entities
{
    public partial class UDP_tbSolicitud_SelectResult
    {
        public int solic_Id { get; set; }
        public string solic_Correo { get; set; }
        public string solic_NombreCompleto { get; set; }
        public DateTime solic_Fecha { get; set; }
        public int masc_Id { get; set; }
        public string masc_Nombre { get; set; }
    }
}
