// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Appets.DataAccess.Entities
{
    public partial class UDP_tbRazas_SelectResult
    {
        public int raza_Id { get; set; }
        public string raza_Descripcion { get; set; }
        public int? espc_Id { get; set; }
        public string espc_Descripcion { get; set; }
    }
}
