// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Appets.DataAccess.Entities
{
    public partial class UDP_tbModuloPantallas_SelectResult
    {
        public int modpan_Id { get; set; }
        public int? mod_Id { get; set; }
        public string mod_Nombre { get; set; }
        public string modpan_Nombre { get; set; }
    }
}
