// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Appets.DataAccess.Entities
{
    public partial class UDP_tbModulos_SelectResult
    {
        public int mod_Id { get; set; }
        public int? comp_Id { get; set; }
        public string comp_Nombre { get; set; }
        public string mod_Nombre { get; set; }
    }
}
